### ISSUE TITLE
panic log file

### ISSUE THREAD

**Issue by css-hacker** [RUB-SysSec/kAFL#11]
hi, @schumilo 

when the guest vm panic,
where can i get the panic log on host machine.

**Comment by schumilo** [comment]
kAFL writes new inputs to `<workdir>/corpus/` and actual findings (such as crashing inputs) to `<workdir>/findings`. If you launch kAFL in `-v` mode, the fuzzer will write debug messages to `debug.log`.

**Comment by css-hacker** [comment]
thanks a lot. @schumilo

**Comment by css-hacker** [comment]
i  misunderstand.
1. debug.log just contain the verbose mode's output? no kernel panic log , is it right?
>i start kafl with 
  python kafl_fuzz.py ... ...  -v --Purge
but no debug.log file,

2. why i need the kernel panic log , 
because just the <workdir>/corpus/ file,  may not enough. 
i have the file, but the panic can not reproduce. 
the panic may depent the syscalls before the one  in the  <workdir>/corpus/ file. 
i test ioctl cmds.

thanks.
