### ISSUE TITLE
Can you provide the compiled windows vulnerable driver?

### ISSUE THREAD

**Issue by alzkejalzkje** [RUB-SysSec/kAFL#17]
For testing purposes it would be much easier to have the compiled windows vulnerable driver or an easy way to have that.
I have been struggling with mingw to get it compile, would you have any way to do it easily?

**Comment by MatthewTingum** [comment]
You can grab the compiled driver here:
https://github.com/MatthewTingum/kAFL/blob/master/kAFL-Fuzzer/vuln_drivers/simple/win10_x86-64/Driver.sys

And the makefile I used here:
https://github.com/MatthewTingum/kAFL/blob/master/kAFL-Fuzzer/vuln_drivers/simple/win10_x86-64/Makefile

I'm still having issues getting this working with Windows so take that with a grain of salt. Driver loads fine, getting at the addresses from host and actually fuzzing are where I'm hung up at. I suppose it could be tested with a known bad input from within guest.

Edit: Driver does in fact work. I had changed the name of the overlay file which can't be done.
