### ISSUE TITLE
Questions in Intel PT decoder

### ISSUE THREAD

**Issue by cheolw00myung** [RUB-SysSec/kAFL#26]
Hello.

Currently, I'm studying kAFL's KVM-PT and QEMU-PT to apply binary kernel fuzzing. So, I modified your kAFL to fit our fuzzer; only QEMU-PT. And I found some errors that occurs when the hypervisor sets the multiple IP ranges  in QEMU-PT's decoder part.

As I understand in Intel PT decoder, after the `pt_disable()` is called, the hypervisor starts decoding about the stored Intel PT packets `decode_buffer()`. However, I got the different results when I set the single IP range (e.g., IP range A) and multiple IP range (e.g., IP range A, and B). For example, if I saw the control flow(ex. a->b->c) in single IP range A, I saw the different control flow(ex. a→d→e) when I set the multiple IP ranges, including a single IP range A.

I kept searching why it happens, and found that it has some errors in decoding the TNT packets. Each decoder which sets different IP ranges got influences from the another IP range's TNT infos.
Therefore, it save the wrong control flows after decoding Intel PT packets.

I think the decoder part needs to be fixed. 

Thank you.

**Comment by chitoge** [comment]
Hi, I think I had the same problem before. I've read that the decoder part is reimplemented in their Redqueen project, and it seems like this project is not actively maintained anymore; maybe you should check it out?

**Comment by cheolw00myung** [comment]
Oh, I didn't think of that. Thank you! 👍 
I will check the REDQEEUN project.
