### ISSUE TITLE
Some troubles when I Prepared VM for kAFL fuzzing

### ISSUE THREAD

**Issue by ChijinZ** [RUB-SysSec/kAFL#7]
I met some troubles when following your instructions.  

1. As your saying:
> Execute loader binary which is in `path/to/kAFL/kAFL-Fuzzer/agents/linux_x86_64/loader/` as root VM should freeze.

I execute loader binary as root but VM didn't freeze. It echoed a sentence that:

> Kernel Panic Handler Address: ffffffff8118d734

Is this a right way?

2. How to Switch to the QEMU management console? I press CTRL-a + c but nothing happenned.

Looking forward to your answer.

**Comment by schumilo** [comment]
Could you please verify that the KVM-PT kernel is loaded (e.g. via executing `uname -a` / `lsmod`) and also ensure that you are using the patched QEMU-PT executable?

**Comment by ChijinZ** [comment]
Thank you for your answering.

I am sure that using the patched QEMU-PT. But I am confused that how to loading the KVM-PT kernel?

I am a green hand on kernel issue. As far as I understand, your `install.sh` download QEMU and Linux kernel and patch them. But the `Linux-$Linux-VERSON` Document which includes KVM-PT is not used in your `README`. So how to loading the KVM-PT kernel?
