### ISSUE TITLE
Problems with "Setup VM" & "Compile and configure kAFL components"

### ISSUE THREAD

**Issue by c2hpxq** [RUB-SysSec/kAFL#8]
Hello there, I meet some problems during installation.
In "Setup VM":
When I run 
`qemu-2.9.0/x86_64-softmmu/qemu-system-x86_64 -cpu host -enable-kvm -m 512 -hda linux.qcow2 -cdrom ubuntu.iso -usbdevice tablet`
I get an error:
`qemu-system-x86_64: error: failed to set MSR 0x38d to 0x0
qemu-system-x86_64: /home/c2hpxq/sectools/kAFL/qemu-2.9.0/target/i386/kvm.c:1833: kvm_put_msrs: Assertion ret == cpu->kvm_msr_buf->nmsrs' failed.`
I've tried use qemu-system-x86_64 installed by apt instead, the error not occurring anymore but when in "Compile and configure kAFL components", I run:
`python kafl_info.py /path/to/snapshot/ram.qcow2 /path/to/snapshot/ agents/linux_x86_64/info/info 512 -v`
I'm told VMX_PT not loaded.

Now I'm trying to comment out assertions in qemu-2.9.0/target/i386/kvm.c (line 1833 & 2204), and the VM installation seems working(I'm still on it when writing this answer)
Do I get anything wrong? What's the right way to do it?

And by the way, when VM installation completed & rebooting, it get stuck at interface "Ubuntu 16.04", not continuing anymore... Kind of weird...

Please help me about it.

Update1:
Still meet the problem
`[Error] VMX_PT is not loaded!`

Update2:
Can I do installation in a Ubuntu 16.04 virtual machine? i.e., qemu vm running in a virtual machine, does that matter?
And where can I find information about whether a CPU supporting PT or not, it seems CPU specification doesn't list it in the product specification page, and I don't find anything useful in intel PT page.
I don't know whether i7-7820HQ & i7-4712MQ are supported or not. I assume the former is supported and doubt the latter.

Hope for your help!

**Comment by stuartly** [comment]
I meet the same problem

[Error] VMX_PT is not loaded! 

Have you solve it ?

**Comment by schumilo** [comment]
`VMX_PT is not loaded` means that the KVM-PT kernel module is missing. You can verify if KVM-PT is loaded by checking `dmesg` for `[VMX-PT] Info:	CPU is supported!` .Otherwise something went wrong. Right now, it is not possible to use Intel PT inside a VM (afaik).
